var abbeyRoadRecords = [{song: "Land of Hope and Glory",
                      artist: "Sir Edward Elgar",
                      month: 11,
                      year: 1931},
                      {song: "Elgar violin concerto",
                      artist: "Yehudi Menuhin",
                      month: 07,
                      year: 1932},
                      {song: "Piano Sonata, Funerailles",
                      artist: "Yehudi Menuhin",
                      month: 11,
                      year: 1932},
                      {song: "",
                      artist: "Richard Tauber",
                      month: 11,
                      year: 1933},
                      {song: "Suits No. 1 & 2 Johann Sebastian Bach's Cello Suites",
                      artist: "Pablo Casals",
                      month: 11,
                      year: 1933},
                      {song: "Suits No. 1 & 2 Johann Sebastian Bach's Cello Suites",
                      artist: "Pablo Casals",
                      month: 11,
                      year: 1936},
                      {song: "I Can't Give You Anything but Love",
                      artist: "Adelaide Hall and Fats Waller",
                      month: 08,
                      year: 1938},
                      {song: "Symphony No. 5",
                      artist: "Vaughan Williams",
                      year: 1943},
                      {artist: "Glenn Miller and Dinah Shore",
                      month: 09,
                      year: 1944},
                      {song: "Quintet for Piano and Winds",
                      artist: "Dennis Brain Wind Ensemble with Colin Horsley",
                      year: 1954},
                      {song: "Move It",
                      artist: "Cliff Richard and the Drifters",
                      year: 1958},
                      {song: "Cliff",
                      artist: "Cliff Richard and the Drifters",
                      year: 1959},
                      {song: "Cliff Sings",
                      artist: "Cliff Richard and the Drifters",
                      year: 1959},
                      {song: "Serious Charge",
                      artist: "Cliff Richard and the Drifters",
                      year: 1959},
                      {song: "Expresso Bongo",
                      artist: "Cliff Richard and The Shadows",
                      year: 1959},
                      {song: "Living Doll",
                      artist: "Cliff Richard and The Shadows",
                      year: 1959},
                      {song: "Travellin' Light",
                      artist: "Cliff Richard and The Shadows",
                      year: 1959},
                      {song: "100 Strings and Joni",
                      artist: "Joni James",
                      year: 1959},
                      {song: "My Thanks to You",
                      artist: "Connie Francis",
                      year: 1959},
                      {song: "Connie Francis Sings Italian Favorites",
                      artist: "Connie Francis",
                      year: 1959},
                      {song: "Christmas in My Heart",
                      artist: "Connie Francis",
                      year: 1959},
                      {song: "One for the Boys",
                      artist: "Joni James",
                      year: 1959},
                      {song: "Me and My Shadows",
                      artist: "Cliff Richard and The Shadows",
                      year: 1960},
                      {song: "Apache",
                      artist: "The Shadows",
                      year: 1960},
                      {song: "Please Don't Tease",
                      artist: "Cliff Richard and The Shadows",
                      year: 1960},
                      {song: "I Love You",
                      artist: "Cliff Richard and The Shadows",
                      year: 1960},
                      {song: "The Shadows",
                      artist: "The Shadows",
                      year: 1960},
                      {song: "(Ghost) Riders in the Sky/Torquay",
                      artist: "The Scorpions",
                      year: 1961},
                      {song: "Rockin' at the Phil/Scorpio",
                      artist: "The Scorpions",
                      year: 1961},
                      {song: "Kon-Tiki",
                      artist: "The Shadows",
                      year: 1961},
                      {song: "The Young Ones",
                      artist: "Cliff Richard and The Shadows",
                      year: 1961},
                      {song: "21 Today",
                      artist: "Cliff Richard and The Shadows",
                      year: 1961},
                      {song: "Listen to Cliff",
                      artist: "Cliff Richard and The Shadows",
                      year: 1961},
                      {song: "The Shadows",
                      artist: "The Shadows",
                      year: 1961},
                      {song: "It's Time to Say Goodnight",
                      artist: "Connie Francis",
                      year: 1961},
                      {song: "Wonderful Land",
                      artist: "The Shadows",
                      year: 1962},
                      {song: "Dance On",
                      artist: "The Shadows",
                      year: 1962},
                      {song: "The Next Time",
                      artist: "Cliff Richard and The Shadows",
                      year: 1962},
                      {song: "The Young Ones",
                      artist: "Cliff Richard and The Shadows",
                      year: 1962},
                      {song: "32 Minutes and 17 Seconds with Cliff Richard",
                      artist: "Cliff Richard and The Shadows",
                      year: 1962},
                      {song: "The Boys",
                      artist: "The Shadows",
                      year: 1962},
                      {song: "Out of The Shadows",
                      artist: "The Shadows",
                      year: 1962},
                      {song: "Foot Tapper",
                      artist: "The Shadows",
                      year: 1963},
                      {song: "Summer Holiday",
                      artist: "Cliff Richard and The Shadows",
                      year: 1963},
                      {song: "When in Spain",
                      artist: "Cliff Richard and The Shadows",
                      year: 1963},
                      {song: "Stay with The Hollies",
                      artist: "The Hollies",
                      year: 1963},
                      {song: "Please Please Me",
                      artist: "The Beatles",
                      year: 1963},
                      {song: "With The Beatles",
                      artist: "The Beatles",
                      year: 1963},
                      {song: "How Do You Do It",
                      artist: "Gerry and the Pacemakers",
                      month: 1,
                      year: 1963},
                      {song: "Dance with The Shadows",
                      artist: "The Shadows",
                      year: 1963},
                      {song: "Wonderful Life",
                      artist: "Cliff Richards and The Shadows",
                      year: 1964},
                      {song: "Ferry Cross the Mersey",
                      artist: "Gerry and the Pacemakers",
                      month: 5,
                      year: 1964},
                      {song: "Aladdin and His Lamp",
                      artist: "Cliff Richards and The Shadows",
                      year: 1964},
                      {song: "A Hard Day's Night",
                      artist: "The Beatles",
                      year: 1964},
                      {song: "In The Hollies Style",
                      artist: "The Hollies",
                      year: 1964},
                      {song: "Beatles for Sale",
                      artist: "The Beatles",
                      year: 1964},
                      {song: "Cliff Richard",
                      artist: "Cliff Richard and The Shadows",
                      year: 1964},
                      {song: "Love is Forever",
                      artist: "Cliff Richard and The Shadows",
                      year: 1965},
                      {song: "The Sound of The Shadows",
                      artist: "The Shadows",
                      year: 1965},
                      {song: "Rhythm and Greens",
                      artist: "The Shadows",
                      year: 1965},
                      {song: "Hollies",
                      artist: "The Hollies",
                      year: 1965},
                      {song: "Help",
                      artist: "The Beatles",
                      year: 1965},
                      {song: "Rubber Soul",
                      artist: "The Beatles",
                      year: 1965},
                      {song: "Sunshine Superman",
                      artist: "Donovan",
                      year: 1966},
                      {song: "Mellow Yellow",
                      artist: "Donovan",
                      year: 1966},
                      {song: "Kinda Latin",
                      artist: "Cliff Richard",
                      year: 1966},
                      {song: "Finders Keepers",
                      artist: "Cliff Richard and The Shadows",
                      year: 1966},
                      {song: "Would You Believe?",
                      artist: "The Hollies",
                      year: 1966},
                      {song: "Shadow Music",
                      artist: "The Shadows",
                      year: 1966},
                      {song: "Splendor in the Grass",
                      artist: "Gullivers People",
                      year: 1966},
                      {song: "Revolver",
                      artist: "The Beatles",
                      year: 1966},
                      {song: "Fi-Fo-Fum",
                      artist: "Gullivers People",
                      year: 1966},
                      {song: "Thunderbirds Are Go",
                      artist: "The Shadows with Cliff Richard",
                      year: 1966},,
                      {song: "For Certain Because",
                      artist: "The Hollies",
                      year: 1967},
                      {song: "Don't Stop Me Now",
                      artist: "Cliff Richard",
                      year: 1967},
                      {song: "Cinderella",
                      artist: "Cliff Richard and The Shadows",
                      year: 1967},
                      {song: "Good News",
                      artist: "Cliff Richard",
                      year: 1967},
                      {song: "Jigsaw",
                      artist: "The Shadows",
                      year: 1967},
                      {song: "From Hank, Bruce, Brian and John",
                      artist: "The Shadows",
                      year: 1967},
                      {song: "Evolution",
                      artist: "The Hollies",
                      year: 1967},
                      {song: "Sgt. Pepper's Lonely Hearts Club Band",
                      artist: "The Beatles",
                      year: 1967},
                      {song: "Odessey and Oracle",
                      artist: "The Zombies",
                      year: 1967},
                      {song: "Magical Mystery Tour",
                      artist: "The Beatles",
                      year: 1967},
                      {song: "Butterfly",
                      artist: "The Hollies",
                      year: 1967},
                      {song: "The Piper at the Gates of Dawn",
                      artist: "Pink Floyd",
                      year: 1967},
                      {song: "Change of Direction",
                      artist: "Brian Bennett",
                      year: 1967},
                      {song: "Established 1958",
                      artist: "Cliff Richard and The Shadows",
                      year: 1968},
                      {song: "Two a Penny",
                      artist: "Cliff Richard",
                      year: 1968},
                      {song: "A Saucerful of Secrets",
                      artist: "Pink Floyd",
                      year: 1968},
                      {song: "S.F. Sorrow",
                      artist: "The Pretty Things",
                      year: 1968},
                      {song: "The Madcap Laughs",
                      artist: "Syd Barrett",
                      year: 1968},
                      {song: "On a Day Like This",
                      artist: "Gullivers People",
                      year: 1968},
                      {song: "Truth",
                      artist: "Jeff Beck with Rod Stewart and Ronnie Wood",
                      year: 1968},
                      {song: "The Beatles (aka 'The White song')",
                      artist: "The Beatles",
                      year: 1968},
                      {song: "Sincerely Cliff",
                      artist: "Cliff Richard",
                      month: 1,
                      year: 1969},
                      {song: "Hollies Sing Dylan",
                      artist: "The Hollies",
                      month: 2,
                      year: 1969},
                      {song: "Soundtrack from the Film More",
                      artist: "Pink Floyd",
                      month: 3,
                      year: 1969},
                      {song: "Hollies Sing Hollies",
                      artist: "The Hollies",
                      month: 3,
                      year: 1969},
                      {song: "Somehow,Somewhere",
                      artist: "Gullivers People",
                      month: 5,
                      year: 1969},
                      {song: "Yellow Submarine",
                      artist: "The Beatles",
                      month: 9,
                      year: 1969},
                      {song: "Hank Marvin",
                      artist: "Hank Marvin",
                      month: 10,
                      year: 1969},
                      {song: "Bloodsucker",
                      artist: "Deep Purple",
                      month: 11,
                      year: 1969},
                      {song: "Shades of Rock",
                      artist: "The Shadows",
                      year: 1970},
                      {song: "Fela's London Scene",
                      artist: "Fela Kuti",
                      year: 1970},
                      {song: "Tracks 'n Grooves",
                      artist: "Cliff Richard",
                      year: 1970},
                      {song: "About That Man",
                      artist: "Cliff Richard",
                      year: 1970},
                      {song: "His Land",
                      artist: "Cliff Richard",
                      year: 1970},
                      {song: "Confessions of the Mind",
                      artist: "The Hollies",
                      year: 1970},
                      {song: "All Things Must Pass",
                      artist: "George Harrison",
                      year: 1970},
                      {song: "Barrett",
                      artist: "Syd Barrett",
                      month: 7,
                      year: 1970},
                      {song: "All Things Must Pass",
                      artist: "George Harrison",
                      year: 1970},
                      {song: "Atom Heart Mother",
                      artist: "Pink Floyd",
                      year: 1970},
                      {song: "CCS",
                      artist: "CCS",
                      year: 1970},
                      {song: "Marvin, Welch & Farrar",
                      artist: "Marvin, Welch & Farrar",
                      year: 1970},
                      {song: "John Lennon/Plastic Ono Band",
                      artist: "John Lennon",
                      year: 1970},
                      {song: "Parachute",
                      artist: "The Pretty Things",
                      year: 1970},
                      {song: "Meddle",
                      artist: "Pink Floyd",
                      year: 1971},
                      {song: "Second Opinion",
                      artist: "Marvin, Welch & Farrar",
                      year: 1971},
                      {song: "Raspberries",
                      artist: "Raspberries",
                      year: 1972},
                      {song: "Hank Marvin and John Farrar",
                      artist: "Marvin and Farrar",
                      year: 1972},
                      {song: "Fresh",
                      artist: "Raspberries",
                      year: 1972},
                      {song: "Afrodisiac",
                      artist: "Fela Kuti",
                      year: 1973},
                      {song: "Take Me High",
                      artist: "Cliff Richard",
                      year: 1973},
                      {song: "The Dark Side of the Moon",
                      artist: "Pink Floyd",
                      year: 1973},
                      {song: "Help It Along",
                      artist: "Cliff Richard",
                      year: 1974},
                      {song: "Kid in a Big World",
                      artist: "John Howard",
                      year: 1974},
                      {song: "Modern Times",
                      artist: "Al Stewart",
                      year: 1975},
                      {song: "Specs Appeal",
                      artist: "The Shadows",
                      year: 1975},
                      {song: "Scheherezade And Other Stories",
                      artist: "Renaissance",
                      year: 1975},
                      {song: "The 31st of February Street",
                      artist: "Cliff Richard",
                      year: 1975},
                      {song: "The Best Years of Our Lives",
                      artist: "Steve Harley & Cockney Rebel",
                      year: 1975},
                      {song: "Honky Tonk Angel",
                      artist: "Cliff Richard",
                      year: 1975},
                      {song: "Run Billy Run",
                      artist: "The Shadows",
                      year: 1975},
                      {song: "Miss You Nights",
                      artist: "Cliff Richard",
                      year: 1975},
                      {song: "Wish You Were Here",
                      artist: "Pink Floyd",
                      year: 1975},
                      {song: "Devil Woman",
                      artist: "Cliff Richard",
                      year: 1976},
                      {song: "I'm Nearly Famous",
                      artist: "Cliff Richard",
                      year: 1976},
                      {song: "Tales of Mystery and Imagination",
                      artist: "The Alan Parsons Project",
                      year: 1976},
                      {song: "Year of the Cat",
                      artist: "Al Stewart",
                      year: 1976},
                      {song: "It'll Be Me Babe",
                      artist: "The Shadows",
                      year: 1976},
                      {song: "Tasty",
                      artist: "The Shadows",
                      year: 1977},
                      {song: "Every Face Tells a Story",
                      artist: "Cliff Richard",
                      year: 1977},
                      {song: "I Robot",
                      artist: "The Alan Parsons Project",
                      year: 1978},
                      {song: "Pyramid",
                      artist: "The Alan Parsons Project",
                      year: 1978},
                      {song: "Love You More/Noise Annoys",
                      artist: "Buzzcocks",
                      year: 1978},
                      {song: "Love de Luxe/Sweet Saturday Night",
                      artist: "The Shadows",
                      year: 1978},
                      {song: "Green Light",
                      artist: "Cliff Richard",
                      year: 1978},
                      {song: "Small Corners",
                      artist: "Cliff Richard",
                      year: 1978},
                      {song: "Go 2",
                      artist: "XTC",
                      year: 1978},
                      {song: "Hank Marvin Guitar Syndicate",
                      artist: "Hank Marvin",
                      year: 1978},
                      {song: "String of Hits",
                      artist: "The Shadows",
                      year: 1979},
                      {song: "Love Don't Live Here Anymore",
                      artist: "Morrissey–Mullen",
                      year: 1979},
                      {song: "Paradise Skies",
                      artist: "Max Webster",
                      year: 1979},
                      {song: "Sky 2",
                      artist: "Sky",
                      year: 1980},
                      {song: "Change of Address",
                      artist: "The Shadows",
                      year: 1980},
                      {song: "Never for Ever",
                      artist: "Kate Bush",
                      year: 1980},
                      {song: "Duran Duran",
                      artist: "Duran Duran",
                      year: 1980},
                      {song: "Raiders of the Lost Ark",
                      artist: "John Williams",
                      year: 1981},
                      {song: "Nude",
                      artist: "Camel",
                      year: 1981},
                      {song: "Live at Abbey Road",
                      artist: "The Shadows",
                      year: 1982},
                      {song: "Eye in the Sky",
                      artist: "The Alan Parsons Project",
                      year: 1982},
                      {song: "Sivilisaatio",
                      artist: "Juice Leskinen Grand Slam",
                      year: 1982},
                      {song: "Burning Bridges",
                      artist: "Naked Eyes",
                      year: 1982},
                      {song: "The Final Cut",
                      artist: "Pink Floyd",
                      year: 1983},
                      {song: "Points on the Curve",
                      artist: "Wang Chung",
                      year: 1983},
                      {song: "Russians and Americans",
                      artist: "Al Stewart",
                      year: 1984},
                      {song: "About Face",
                      artist: "David Gilmour",
                      year: 1984},
                      {song: "Ammonia Avenue",
                      artist: "The Alan Parsons Project",
                      year: 1984},
                      {song: "Vulture Culture",
                      artist: "The Alan Parsons Project",
                      year: 1985},
                      {song: "Power Windows",
                      artist: "Rush",
                      year: 1985},
                      {song: "Signos",
                      artist: "Soda Stereo",
                      year: 1986},
                      {song: "Delicate Sound of Thunder",
                      artist: "Pink Floyd",
                      year: 1988},
                      {song: "Inspiration",
                      artist: "Elkie Brooks",
                      year: 1989},
                      {song: "Phantom Manor at Disneyland Paris",
                      artist: "Phantom Manor at Disneyland Paris",
                      year: 1990},
                      {song: "Come l'acqua",
                      artist: "Mango",
                      year: 1992},
                      {song: "Amused to Death",
                      artist: "Roger Waters",
                      year: 1992},
                      {song: "Pablo Honey",
                      artist: "Radiohead",
                      year: 1993},
                      {song: "The Division Bell",
                      artist: "Pink Floyd",
                      year: 1994},
                      {song: "Ponk!!",
                      artist: "Seikima-II",
                      year: 1994},
                      {song: "Wonderful",
                      artist: "Adam Ant",
                      year: 1994},
                      {song: "The Bends",
                      artist: "Radiohead",
                      year: 1995},
                      {song: "To The End (La Comedie)",
                      artist: "Blur with Françoise Hardy",
                      year: 1995},
                      {song: "Come Together",
                      artist: "The Smokin' Mojo Filters",
                      month: 9,
                      year: 1995},
                      {song: "Everything Must Go",
                      artist: "Manic Street Preachers",
                      year: 1996},
                      {song: "Rotator",
                      artist: "Dizzy Mizz Lizzy",
                      year: 1996},
                      {song: "Razorblade Suitcase",
                      artist: "Bush",
                      year: 1996},
                      {song: "Knockin' on Heaven's Door/Throw These Guns Away",
                      artist: "Dunblane",
                      year: 1996},
                      {song: "Ultra",
                      artist: "Depeche Mode",
                      year: 1996},
                      {song: "Terraform",
                      artist: "Shellac",
                      year: 1996},
                      {song: "Towers Open Fire",
                      artist: "Guapo",
                      year: 1997},
                      {song: "Be Here Now",
                      artist: "Oasis",
                      year: 1997},
                      {song: "OK Computer",
                      artist: "Radiohead",
                      year: 1997},
                      {song: "Deeper Underground",
                      artist: "Jamiroquai",
                      year: 1997},
                      {song: "Fireworks",
                      artist: "Angra",
                      year: 1998},
                      {song: "This Is My Truth Tell Me Yours",
                      artist: "Manic Street Preachers",
                      year: 1998},
                      {song: "Bluesugar",
                      artist: "Zucchero",
                      year: 1998},
                      {song: "Bocanada",
                      artist: "Gustavo Cerati",
                      year: 1999},
                      {song: "Apple Venus Volume 1",
                      artist: "XTC",
                      year: 1999},
                      {song: "Narigón Del Siglo",
                      artist: "Divididos",
                      year: 1999},
                      {song: "Brothers & Sisters EP",
                      artist: "Coldplay",
                      year: 1999},
                      {song: "Bawitdaba",
                      artist: "Kid Rock",
                      year: 1999},
                      {song: "Parvaaz",
                      artist: "Junoon",
                      year: 1999},
                      {song: "Modern",
                      artist: "Buzzcocks",
                      year: 1999},
                      {song: "Still",
                      artist: "Alanis Morissette",
                      year: 1999},
                      {song: "Metal Jukebox",
                      artist: "Helloween",
                      year: 1999},
                      {song: "Watercolours",
                      artist: "Jason Kouchak",
                      year: 2000},
                      {song: "Figure 8",
                      artist: "Elliott Smith",
                      year: 2000},
                      {song: "Lightbulb Sun",
                      artist: "Porcupine Tree",
                      year: 2000},
                      {song: "Narigon Del Siglo",
                      artist: "Divididos",
                      year: 2000},
                      {song: "Kid A",
                      artist: "Radiohead",
                      year: 2000},
                      {song: "No More Shall We Part",
                      artist: "Nick Cave and the Bad Seeds",
                      year: 2000},
                      {song: "Know Your Enemy",
                      artist: "Manic Street Preachers",
                      year: 2001},
                      {song: "Origin of Symmetry",
                      artist: "Muse",
                      year: 2001},
                      {song: "We Love Life",
                      artist: "Pulp",
                      year: 2001},
                      {song: "Blackened Sky",
                      artist: "Biffy Clyro",
                      year: 2002},
                      {song: "Dopamin",
                      artist: "Böhse Onkelz",
                      year: 2002},
                      {song: "Shamans",
                      artist: "Aziza Mustafa Zadeh",
                      year: 2002},
                      {song: "East Meets East",
                      artist: "Nigel Kennedy and Kroke",
                      year: 2003},
                      {song: "The Vertigo of Bliss",
                      artist: "Biffy Clyro",
                      year: 2003},
                      {song: "Effloresce",
                      artist: "Oceansize",
                      year: 2003},
                      {song: "Coldplay Live 2003",
                      artist: "Coldplay",
                      year: 2003},
                      {song: "Christmas Time (Don't Let the Bells End)",
                      artist: "The Darkness",
                      year: 2003},
                      {song: "Free the Bees",
                      artist: "The Bees",
                      year: 2004},
                      {song: "Blackfield",
                      artist: "Blackfield",
                      year: 2004},
                      {song: "Songs of Darkness, Words of Light",
                      artist: "My Dying Bride",
                      year: 2004},
                      {song: "Infinity Land",
                      artist: "Biffy Clyro",
                      year: 2004},
                      {song: "ClassiKhan",
                      artist: "Chaka Khan",
                      year: 2004},
                      {song: "Live at Abbey Road Studios 2004",
                      artist: "Tim Christensen",
                      year: 2004},
                      {song: "The Abbey Road Sessions",
                      artist: "Steven Curtis Chapman",
                      year: 2005},
                      {song: "Extraordinary Machine",
                      artist: "Fiona Apple",
                      year: 2005},
                      {song: "By Myself, The Songs of Judy Garland",
                      artist: "Linda Eder",
                      year: 2005},
                      {song: "Everyone Into Position",
                      artist: "Oceansize",
                      year: 2005},
                      {song: "Late Orchestration",
                      artist: "Kanye West",
                      year: 2005},
                      {song: "U218 Singles",
                      artist: "U2",
                      year: 2006},
                      {song: "On An Island",
                      artist: "David Gilmour",
                      year: 2006},
                      {song: "From My Heart",
                      artist: "Giorgia Fumanti",
                      year: 2006},
                      {song: "Porque Soy Tempo",
                      artist: "Tempo featuring The London Symphony Orchestra",
                      year: 2006},
                      {song: "Somewhere Else",
                      artist: "Marillion",
                      year: 2007},
                      {song: "Dark Passion Play",
                      artist: "Nightwish",
                      year: 2007},
                      {song: "Dark Passion Play",
                      artist: "Travis",
                      year: 2007},
                      {song: "Music of the Spheres",
                      artist: "Mike Oldfield",
                      year: 2007},
                      {song: "Time Machine",
                      artist: "Mashina Vremeni",
                      year: 2008},
                      {song: "Oogie Boogie's Song",
                      artist: "Rodrigo y Gabriela",
                      year: 2008},
                      {song: "Dig Out Your Soul",
                      artist: "Oasis",
                      year: 2008},
                      {song: "To Know That You're Alive",
                      artist: "Kutless",
                      year: 2008},
                      {song: "Running to Catch",
                      artist: "Steve Wilson (of Steve Wilson Band)",
                      year: 2008},
                      {song: "With This Ship",
                      artist: "The Basics",
                      year: 2008},
                      {song: "Pretty. Odd.",
                      artist: "Panic! at the Disco",
                      year: 2008},
                      {song: "Cesarians 1",
                      artist: "The Cesarians",
                      year: 2008},
                      {song: "The Butterfly Effect",
                      artist: "Diana Yukawa",
                      year: 2009},
                      {song: "Home & Minor",
                      artist: "Oceansize",
                      year: 2009},
                      {song: "My Christmas",
                      artist: "Andrea Bocelli",
                      year: 2009},
                      {song: "Road To Abbey",
                      artist: "J-Rocks",
                      year: 2009},
                      {song: "Echo",
                      artist: "Leona Lewis",
                      year: 2009},
                      {song: "Keep Your Friends Close",
                      artist: "The Basics",
                      year: 2009},
                      {song: "Roupa Nova em Londres",
                      artist: "Roupa Nova",
                      year: 2009},
                      {song: "400 Years of the Telescope, A Journey of Science, Technology and Thought",
                      artist: "Mark Slater",
                      year: 2009},
                      {song: "The Piano Dreamer",
                      artist: "Jan Mulder with The London Symphony Orchestra",
                      year: 2010},
                      {song: "Il Volo",
                      artist: "Il Volo",
                      year: 2010},
                      {song: "What is Love?",
                      artist: "Never Shout Never",
                      year: 2010},
                      {song: "World of Color",
                      artist: "Disney California Adventure Park",
                      year: 2010},
                      {song: "Love God. Love People.",
                      artist: "Israel Houghton",
                      year: 2010},
                      {song: "The Drums",
                      artist: "The Drums",
                      year: 2010},
                      {song: "/ðəˈbæzɪtʃ/",
                      artist: "The Basics",
                      year: 2010},
                      {song: "Symphonicities",
                      artist: "Sting",
                      year: 2010},
                      {song: "Self Preserved While the Bodies Float Up",
                      artist: "Oceansize",
                      year: 2010},
                      {song: "Progress",
                      artist: "Take That",
                      year: 2010},
                      {song: "Hedonism",
                      artist: "Bellowhead",
                      year: 2010},
                      {song: "The Fall",
                      artist: "Gorillaz",
                      year: 2010},
                      {song: "L.A. Noire Official Soundtrack",
                      artist: "Andrew Hale, Simon Hale, Woody Jackson...",
                      year: 2011},
                      {song: "Born This Way",
                      artist: "Lady Gaga",
                      year: 2011},
                      {song: "Body & Soul",
                      artist: "Tony Bennett & Amy Winehouse",
                      year: 2011},
                      {song: "Fantasmic!",
                      artist: "Royal Philharmonic Orchestra for Tokyo DisneySea",
                      year: 2011},
                      {song: "Jhoom",
                      artist: "Ali Zafar",
                      year: 2011},
                      {song: "Ceremonials",
                      artist: "Florence and The Machine",
                      year: 2011},
                      {song: "TRU",
                      artist: "Instrumenti",
                      year: 2011},
                      {song: "Unmistakable",
                      artist: "Oscar Peterson",
                      year: 2011},
                      {song: "Ahora",
                      artist: "Pedro Aznar",
                      year: 2012},
                      {song: "The Abbey Road Sessions",
                      artist: "Kylie Minogue",
                      year: 2012},
                      {song: "Bish Bosch",
                      artist: "Scott Walker",
                      year: 2012},
                      {song: "Sriwedari",
                      artist: "Maliq & D'Essentials",
                      year: 2013},
                      {song: "Inside and Out",
                      artist: "Lucinda Nicholls",
                      year: 2013},
                      {song: "Rachmaninoff: The Piano Concertos",
                      artist: "Valentina Lisitsa, and the London Symphony Orchestra",
                      year: 2013},
                      {song: "Swings Both Ways",
                      artist: "Robbie Williams",
                      year: 2013},
                      {song: "Love Divine II",
                      artist: "Jan Mulder with The London Symphony Orchestra",
                      year: 2014},
                      {song: "Come Find Me",
                      artist: "Fox Amoore",
                      year: 2014},
                      {song: "Live At Abbey",
                      artist: "Gigi",
                      year: 2014},
                      {song: "The London Session",
                      artist: "Umphrey's McGee",
                      year: 2014},
                      {song: "Pirohia",
                      artist: "Kerretta",
                      year: 2014},
                      {song: "Soused",
                      artist: "Sunn O",
                      year: 2014},
                      {song: "The Lucky Country",
                      artist: "The Basics",
                      year: 2014},
                      {song: "Holiday for Swing",
                      artist: "Seth MacFarlane",
                      year: 2014},
                      {song: "Primeira Fila",
                      artist: "Roberto Carlos",
                      year: 2015},
                      {song: "The Age of Entitlement",
                      artist: "The Basics",
                      year: 2015},
                      {song: "No One Ever Tells You",
                      artist: "Seth MacFarlane",
                      year: 2015},
                      {song: "Naked at the Abbey",
                      artist: "Motopony",
                      year: 2015},
                      {song: "Fear Without Progression",
                      artist: "The Aultones",
                      year: 2015},
                      {song: "Love Divine III",
                      artist: "Jan Mulder with The Royal Philharmonic Orchestra",
                      year: 2016}];
