var abbeyRoadRecords = [{song: "Land of Hope and Glory",
                      artist: "Sir Edward Elgar",
                      month: 11,
                      year: 1931},
                      {song: "Elgar violin concerto",
                      artist: "Yehudi Menuhin",
                      month: 07,
                      year: 1932},
                      {song: "Piano Sonata, Funerailles",
                      artist: "Yehudi Menuhin",
                      month: 11,
                      year: 1932},
                      {song: "",
                      artist: "Richard Tauber",
                      month: 11,
                      year: 1933},
                      {song: "Suits No. 1 & 2 Johann Sebastian Bach's Cello Suites",
                      artist: "Pablo Casals",
                      month: 11,
                      year: 1933},
                      {song: "Suits No. 1 & 2 Johann Sebastian Bach's Cello Suites",
                      artist: "Pablo Casals",
                      month: 11,
                      year: 1936},
                      {song: "I Can't Give You Anything but Love",
                      artist: "Adelaide Hall and Fats Waller",
                      month: 08,
                      year: 1938},
                      {song: "Symphony No. 5",
                      artist: "Vaughan Williams",
                      year: 1943},
                      {artist: "Glenn Miller and Dinah Shore",
                      month: 09,
                      year: 1944},
                      {song: "Quintet for Piano and Winds",
                      artist: "Dennis Brain Wind Ensemble with Colin Horsley",
                      year: 1954},
                      {song: "Move It",
                      artist: "Cliff Richard and the Drifters",
                      year: 1958},
                      {song: "Cliff",
                      artist: "Cliff Richard and the Drifters",
                      year: 1959},
                      {song: "Cliff Sings",
                      artist: "Cliff Richard and the Drifters",
                      year: 1959},
                      {song: "Serious Charge",
                      artist: "Cliff Richard and the Drifters",
                      year: 1959},
                      {song: "Expresso Bongo",
                      artist: "Cliff Richard and The Shadows",
                      year: 1959},
                      {song: "Living Doll",
                      artist: "Cliff Richard and The Shadows",
                      year: 1959},
                      {song: "Travellin' Light",
                      artist: "Cliff Richard and The Shadows",
                      year: 1959},
                      {song: "100 Strings and Joni",
                      artist: "Joni James",
                      year: 1959},
                      {song: "My Thanks to You",
                      artist: "Connie Francis",
                      year: 1959},
                      {song: "Connie Francis Sings Italian Favorites",
                      artist: "Connie Francis",
                      year: 1959},
                      {song: "Christmas in My Heart",
                      artist: "Connie Francis",
                      year: 1959},
                      {song: "One for the Boys",
                      artist: "Joni James",
                      year: 1959},
                      {song: "Me and My Shadows",
                      artist: "Cliff Richard and The Shadows",
                      year: 1960},
                      {song: "Apache",
                      artist: "The Shadows",
                      year: 1960},
                      {song: "Please Don't Tease",
                      artist: "Cliff Richard and The Shadows",
                      year: 1960},
                      {song: "I Love You",
                      artist: "Cliff Richard and The Shadows",
                      year: 1960},
                      {song: "The Shadows",
                      artist: "The Shadows",
                      year: 1960},
                      {song: "(Ghost) Riders in the Sky/Torquay",
                      artist: "The Scorpions",
                      year: 1961},
                      {song: "Rockin' at the Phil/Scorpio",
                      artist: "The Scorpions",
                      year: 1961},
                      {song: "Kon-Tiki",
                      artist: "The Shadows",
                      year: 1961},
                      {song: "The Young Ones",
                      artist: "Cliff Richard and The Shadows",
                      year: 1961},
                      {song: "21 Today",
                      artist: "Cliff Richard and The Shadows",
                      year: 1961},
                      {song: "Listen to Cliff",
                      artist: "Cliff Richard and The Shadows",
                      year: 1961},
                      {song: "The Shadows",
                      artist: "The Shadows",
                      year: 1961},
                      {song: "It's Time to Say Goodnight",
                      artist: "Connie Francis",
                      year: 1961},
                      {song: "Wonderful Land",
                      artist: "The Shadows",
                      year: 1962},
                      {song: "Dance On",
                      artist: "The Shadows",
                      year: 1962},
                      {song: "The Next Time",
                      artist: "Cliff Richard and The Shadows",
                      year: 1962},
                      {song: "The Young Ones",
                      artist: "Cliff Richard and The Shadows",
                      year: 1962},
                      {song: "32 Minutes and 17 Seconds with Cliff Richard",
                      artist: "Cliff Richard and The Shadows",
                      year: 1962},
                      {song: "The Boys",
                      artist: "The Shadows",
                      year: 1962},
                      {song: "Out of The Shadows",
                      artist: "The Shadows",
                      year: 1962},
                      {song: "Foot Tapper",
                      artist: "The Shadows",
                      year: 1963},
                      {song: "Summer Holiday",
                      artist: "Cliff Richard and The Shadows",
                      year: 1963},
                      {song: "When in Spain",
                      artist: "Cliff Richard and The Shadows",
                      year: 1963},
                      {song: "Stay with The Hollies",
                      artist: "The Hollies",
                      year: 1963},
                      {song: "Please Please Me",
                      artist: "The Beatles",
                      year: 1963},
                      {song: "With The Beatles",
                      artist: "The Beatles",
                      year: 1963},
                      {song: "How Do You Do It",
                      artist: "Gerry and the Pacemakers",
                      month: 1,
                      year: 1963},
                      {song: "Dance with The Shadows",
                      artist: "The Shadows",
                      year: 1963},
                      {song: "Wonderful Life",
                      artist: "Cliff Richards and The Shadows",
                      year: 1964},
                      {song: "Ferry Cross the Mersey",
                      artist: "Gerry and the Pacemakers",
                      month: 5,
                      year: 1964},
                      {song: "Aladdin and His Lamp",
                      artist: "Cliff Richards and The Shadows",
                      year: 1964},
                      {song: "A Hard Day's Night",
                      artist: "The Beatles",
                      year: 1964},
                      {song: "In The Hollies Style",
                      artist: "The Hollies",
                      year: 1964},
                      {song: "Beatles for Sale",
                      artist: "The Beatles",
                      year: 1964},
                      {song: "Cliff Richard",
                      artist: "Cliff Richard and The Shadows",
                      year: 1964},
                      {song: "Love is Forever",
                      artist: "Cliff Richard and The Shadows",
                      year: 1965},
                      {song: "The Sound of The Shadows",
                      artist: "The Shadows",
                      year: 1965},
                      {song: "Rhythm and Greens",
                      artist: "The Shadows",
                      year: 1965},
                      {song: "Hollies",
                      artist: "The Hollies",
                      year: 1965},
                      {song: "Help",
                      artist: "The Beatles",
                      year: 1965},
                      {song: "Rubber Soul",
                      artist: "The Beatles",
                      year: 1965},
                      {song: "Sunshine Superman",
                      artist: "Donovan",
                      year: 1966},
                      {song: "Mellow Yellow",
                      artist: "Donovan",
                      year: 1966},
                      {song: "Kinda Latin",
                      artist: "Cliff Richard",
                      year: 1966},
                      {song: "Finders Keepers",
                      artist: "Cliff Richard and The Shadows",
                      year: 1966},
                      {song: "Would You Believe?",
                      artist: "The Hollies",
                      year: 1966},
                      {song: "Shadow Music",
                      artist: "The Shadows",
                      year: 1966},
                      {song: "Splendor in the Grass",
                      artist: "Gullivers People",
                      year: 1966},
                      {song: "Revolver",
                      artist: "The Beatles",
                      year: 1966},
                      {song: "Fi-Fo-Fum",
                      artist: "Gullivers People",
                      year: 1966},
                      {song: "Thunderbirds Are Go",
                      artist: "The Shadows with Cliff Richard",
                      year: 1966} ];



var abbeyRoadRecordsNovember = _.filter(abbeyRoadRecords, { 'month': 11});

var grouped = _.groupBy(abbeyRoadRecordsNovember, artist => artist.artist);

var novemberArtists = function () {
  var maximo = 0;
  var autor = "";
  for (var i = 0; i < Object.keys(grouped).length; i++){
    if(grouped[Object.keys(grouped)[i]].length > maximo){
      maximo = grouped[Object.keys(grouped)[i]].length;
      autor = Object.keys(grouped)[i];
    }
  }
  return autor;
};

console.log(novemberArtists());


var artistaDiscos = _.countBy(abbeyRoadRecords, 'artist');


var bestArtist = function () {
  var max = 0;
  var autor = "";
  for (var property in artistaDiscos) {
      if (artistaDiscos.hasOwnProperty(property)) {
        if(artistaDiscos[property] > max){
          max = artistaDiscos[property];
          autor = property;
        }
      }
  }
  return autor;
};

console.log(bestArtist());
